name: Boss Alert

on:
  schedule:
    - cron: '*/5 * * * *'  # chạy mỗi 5 phút
  workflow_dispatch:       # cho phép chạy thủ công

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install pytz requests
      - name: Run bot alert
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
